behaviors:
  SeekerBehavior:
    trainer_type: ppo
    checkpoint_interval: 50000
    hyperparameters:
      batch_size: 3000
      buffer_size: 50000
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 300
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      memory:
        memory_size: 128
    reward_signals:
      extrinsic:
        gamma: 0.998
        strength: 1.0
    max_steps: 3000000
    time_horizon: 160
    summary_freq: 10000

  HiderBehavior:
    trainer_type: ppo
    checkpoint_interval: 50000
    hyperparameters:
      batch_size: 3000
      buffer_size: 50000
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 300
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      memory:
        memory_size: 128
    reward_signals:
      extrinsic:
        gamma: 0.998
        strength: 1.0
    max_steps: 3000000
    time_horizon: 160
    summary_freq: 10000
